name: Validate Patterns

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Pattern Files
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
          
      - name: Install ajv-cli
        run: npm install -g ajv-cli
        
      - name: Validate Patterns
        id: validate-patterns
        run: |
          echo "Validating pattern files against schema..."
          for pattern in patterns/*.json; do
            echo "Checking $pattern"
            ajv validate -s schemas/pattern.schema.json -d "$pattern"
          done

      - name: Status Check
        run: |
          if [ $? -eq 0 ]; then
            echo "::set-output name=status::success"
          else
            echo "::set-output name=status::failure"
            exit 1
          fi 